apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.bridgeaudio.module'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "com.bridgeaudio.module"
  defaultConfig {
    minSdkVersion getDefaultConfig().minSdkVersion
    targetSdkVersion getDefaultConfig().targetSdkVersion
  }
  compileSdkVersion getDefaultConfig().compileSdkVersion
}

dependencies {
  // AudioRecord/AudioTrack and Bluetooth APIs are part of the Android SDK; no extra deps needed.
}
